name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify Node.js version here

      # Install pnpm
      - name: Install pnpm
        run: |
          npm install -g pnpm  # Install pnpm globally

      # Install dependencies using pnpm
      - name: Install dependencies
        run: |
          pnpm install  # This uses pnpm to install dependencies

      # Run tests
      - name: Run tests
        run: |
          pnpm run test  # Run tests using pnpm

      # Build the project
      - name: Build project
        run: |
          pnpm run build  # Build the project using pnpm




