name: CI Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # This uses the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the code to the runner

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your Node.js version here

      - name: Install dependencies
        run: |
          npm install  # or use 'pnpm install' if you're using pnpm

      - name: Run tests
        run: |
          npm run test  # This runs your tests (adjust if necessary)

      - name: Build project
        run: |
          npm run build  # Runs the build script for your Vite project



