name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js v18.12 or higher
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12'

      # Cache pnpm store to speed up subsequent installs
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Install pnpm
      - name: Install pnpm
        run: |
          npm install -g pnpm  # Install pnpm globally

      # Install dependencies for packages/ui
      - name: Install dependencies for packages/ui
        run: |
          cd packages/ui
          pnpm install  # Install dependencies for the ui package

      # Install dependencies for apps/vite-dashboard
      - name: Install dependencies for apps/vite-dashboard
        run: |
          cd apps/vite-dashboard
          pnpm install  # Install dependencies for the vite-dashboard app

      # Install dependencies for the root monorepo
      - name: Install root dependencies
        run: |
          pnpm install  # Install dependencies for the monorepo (if any)

      # Run tests
      - name: Run tests
        run: |
          pnpm run test  # Run tests using pnpm

      # Build the project
      - name: Build project
        run: |
          pnpm run build  # Build the project using pnpm









